
const NEWS = {
	API_FETCH_ALL: 'NEWS_API_FETCH_ALL',
	API_FETCH: 'NEWS_API_FETCH',
	API_CREATE: 'NEWS_API_CREATE',
	API_UPDATE: 'NEWS_API_UPDATE',
	API_DELETE: 'NEWS_API_DELETE'
}

const PASSWORD = {
	API_CHANGE: 'PASSWORD_API_CHANGE',
	API_FORGOT: 'PASSWORD_API_FORGOT',
	API_RESET: 'PASSWORD_API_RESET'
}

const SESSION = {
	API_CREATE: 'SESSION_API_CREATE',
	API_DELETE: 'SESSION_API_DELETE'
}

const TODO = {
	API_FETCH_ALL: 'TODO_API_FETCH_ALL',
	API_CREATE: 'TODO_API_CREATE',
	API_UPDATE: 'TODO_API_UPDATE',
	API_DELETE: 'TODO_API_DELETE',
	API_DELETE_COMPLETED: 'TODO_API_DELETE_COMPLETED',

	UPDATE_SEARCH_QUERY: 'TODO_UPDATE_SEARCH_QUERY',
	UPDATE_DONE_FILTER: 'TODO_UPDATE_DONE_FILTER'
}

const USER = {
	API_FETCH_ALL: 'USER_API_FETCH_ALL',
	API_FETCH: 'USER_API_FETCH',
	API_CREATE: 'USER_API_CREATE',
	API_UPDATE: 'USER_API_UPDATE',
	API_DELETE: 'USER_API_DELETE'
}

export {
	NEWS,
	PASSWORD,
	SESSION,
	TODO,
	USER
}
