
export const FETCH_ALL_NEWS_PREFIX = 'FETCH_ALL_NEWS';
export const FETCH_ALL_NEWS_PENDING = 'FETCH_ALL_NEWS_PENDING';
export const FETCH_ALL_NEWS_FULFILLED = 'FETCH_ALL_NEWS_FULFILLED';
export const FETCH_ALL_NEWS_REJECTED = 'FETCH_ALL_NEWS_REJECTED';
